export default {
  THEME_CHANGE: "THEME_CHANGE", // 主题
  THEME_INIT: "THEME_INIT",

  // 最热 模块
  POPULAR_REFRESH: "POPULAR_REFRESH", // 列表下拉刷新
  POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",  // 下拉刷新成功
  POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",  // 下拉刷新失败
  POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",  // 上拉加载更多成功
  POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",  // 上拉加载更多失败

  // 趋势 模块
  TRENDING_REFRESH: "TRENDING_REFRESH", // 列表下拉刷新
  TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",  // 下拉刷新成功
  TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",  // 下拉刷新失败
  TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",  // 上拉加载更多成功
  TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",  // 上拉加载更多失败

  FLUSH_POPULAR_FAVORITE: "FLUSH_POPULAR_FAVORITE",  // 刷新收藏状态
}
