export default {
  THEME_CHANGE: "THEME_CHANGE", // 主题
  THEME_INIT: "THEME_INIT",

  POPULAR_REFRESH: "POPULAR_REFRESH", // 列表下拉刷新
  LOAD_POPULAR_FAIL: "LOAD_POPULAR_FAIL",  // 列表加载失败
  LOAD_POPULAR_SUCCESS: "LOAD_POPULAR_SUCCESS",  // 列表加载成功

  POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",  // 下拉刷新成功
  POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",  // 下拉刷新失败
  POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",  // 上拉加载更多成功
  POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",  // 上拉加载更多失败
  FLUSH_POPULAR_FAVORITE: "FLUSH_POPULAR_FAVORITE",  // 刷新收藏状态
}
